/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Cameron
 */
public class ConfirmationJPanel extends javax.swing.JPanel {

    /**
     * Creates new form confirmationJPanel
     */
    public ConfirmationJPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        orderStatusLabel = new javax.swing.JLabel();
        thankYouLabel = new javax.swing.JLabel();
        orderNumberLabel = new javax.swing.JLabel();
        orderNumberDIsplay = new javax.swing.JLabel();
        finished = new javax.swing.JButton();

        orderStatusLabel.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        orderStatusLabel.setText("Order Confirmation");
        orderStatusLabel.setFocusCycleRoot(true);

        thankYouLabel.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        thankYouLabel.setText("Thank you for your order!");

        orderNumberLabel.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        orderNumberLabel.setText("Order #");

        orderNumberDIsplay.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        orderNumberDIsplay.setText("orderNumberDisplay");

        finished.setText("Finished");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addComponent(orderStatusLabel)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(345, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(thankYouLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 430, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(305, 305, 305))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(finished, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(orderNumberLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(orderNumberDIsplay)))
                        .addGap(341, 341, 341))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(orderStatusLabel)
                .addGap(100, 100, 100)
                .addComponent(thankYouLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(orderNumberLabel)
                    .addComponent(orderNumberDIsplay))
                .addGap(63, 63, 63)
                .addComponent(finished, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(158, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton finished;
    private javax.swing.JLabel orderNumberDIsplay;
    private javax.swing.JLabel orderNumberLabel;
    private javax.swing.JLabel orderStatusLabel;
    private javax.swing.JLabel thankYouLabel;
    // End of variables declaration//GEN-END:variables
}
