/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Cameron
 */
public class StatusJPanel extends javax.swing.JPanel {

    /**
     * Creates new form statusJFrame
     */
    public StatusJPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        orderAnotherItem = new javax.swing.JButton();
        completeOrder = new javax.swing.JButton();
        orderSummaryLabel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        summaryTextField = new javax.swing.JTextPane();
        orderStatusLabel = new javax.swing.JLabel();

        orderAnotherItem.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        orderAnotherItem.setText("Order Another Item");

        completeOrder.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        completeOrder.setText("Complete Order");

        orderSummaryLabel.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        orderSummaryLabel.setText("Order Summary");

        summaryTextField.setText("ORDER SUMMARY GOES HERE");
        jScrollPane1.setViewportView(summaryTextField);

        orderStatusLabel.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        orderStatusLabel.setText("Order Status");
        orderStatusLabel.setFocusCycleRoot(true);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(230, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(completeOrder, javax.swing.GroupLayout.PREFERRED_SIZE, 361, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(orderAnotherItem, javax.swing.GroupLayout.PREFERRED_SIZE, 361, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(193, 193, 193)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(orderSummaryLabel))
                .addGap(64, 64, 64))
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(orderStatusLabel)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(orderStatusLabel)
                .addGap(75, 75, 75)
                .addComponent(orderAnotherItem, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(completeOrder, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(76, Short.MAX_VALUE)
                .addComponent(orderSummaryLabel)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 417, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(60, 60, 60))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton completeOrder;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton orderAnotherItem;
    private javax.swing.JLabel orderStatusLabel;
    private javax.swing.JLabel orderSummaryLabel;
    private javax.swing.JTextPane summaryTextField;
    // End of variables declaration//GEN-END:variables
}
