/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Cameron
 */
public class ToppingsJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ToppingsJPanel
     */
    public ToppingsJPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        toppingsMenuLabel = new javax.swing.JLabel();
        wheat = new javax.swing.JButton();
        white = new javax.swing.JButton();
        wholeGrain = new javax.swing.JButton();
        cheeseLabel = new javax.swing.JLabel();
        breadsLabel = new javax.swing.JLabel();
        meatsLabel = new javax.swing.JLabel();
        multiGrain = new javax.swing.JButton();
        turkey = new javax.swing.JButton();
        roastbeef = new javax.swing.JButton();
        bologna = new javax.swing.JButton();
        pepperJack = new javax.swing.JButton();
        provolone = new javax.swing.JButton();
        american = new javax.swing.JButton();
        ham = new javax.swing.JButton();
        swiss = new javax.swing.JButton();

        setPreferredSize(new java.awt.Dimension(1080, 600));

        toppingsMenuLabel.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        toppingsMenuLabel.setText("Choose Your Toppings");
        toppingsMenuLabel.setFocusCycleRoot(true);

        wheat.setText("Wheat");
        wheat.setPreferredSize(new java.awt.Dimension(90, 30));

        white.setText("White");
        white.setPreferredSize(new java.awt.Dimension(90, 30));
        white.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                whiteActionPerformed(evt);
            }
        });

        wholeGrain.setText("Whole Grain");
        wholeGrain.setPreferredSize(new java.awt.Dimension(90, 30));

        cheeseLabel.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        cheeseLabel.setText("Cheese");

        breadsLabel.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        breadsLabel.setText("Breads");

        meatsLabel.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        meatsLabel.setText("Meats");

        multiGrain.setText("Multi Grain");
        multiGrain.setPreferredSize(new java.awt.Dimension(90, 30));

        turkey.setText("Turkey");
        turkey.setPreferredSize(new java.awt.Dimension(90, 30));

        roastbeef.setText("Roast Beef");
        roastbeef.setPreferredSize(new java.awt.Dimension(90, 30));

        bologna.setText("Bologna");
        bologna.setPreferredSize(new java.awt.Dimension(90, 30));

        pepperJack.setText("Pepper Jack");
        pepperJack.setPreferredSize(new java.awt.Dimension(90, 30));

        provolone.setText("Provolone");
        provolone.setPreferredSize(new java.awt.Dimension(90, 30));

        american.setText("American");
        american.setPreferredSize(new java.awt.Dimension(90, 30));

        ham.setText("Ham");
        ham.setPreferredSize(new java.awt.Dimension(90, 30));

        swiss.setText("Swiss");
        swiss.setPreferredSize(new java.awt.Dimension(90, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addComponent(toppingsMenuLabel))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(94, 94, 94)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(white, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(wheat, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(multiGrain, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(wholeGrain, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(cheeseLabel)
                                .addComponent(meatsLabel)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(ham, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(turkey, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(roastbeef, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(bologna, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(breadsLabel))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(american, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(provolone, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(pepperJack, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(swiss, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(248, 431, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(toppingsMenuLabel)
                .addGap(54, 54, 54)
                .addComponent(breadsLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(white, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(meatsLabel))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(wheat, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(wholeGrain, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(multiGrain, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ham, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(turkey, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(roastbeef, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bologna, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 23, Short.MAX_VALUE)
                .addComponent(cheeseLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(american, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(provolone, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pepperJack, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(swiss, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(192, 192, 192))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void whiteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_whiteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_whiteActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton american;
    private javax.swing.JButton bologna;
    private javax.swing.JLabel breadsLabel;
    private javax.swing.JLabel cheeseLabel;
    private javax.swing.JButton ham;
    private javax.swing.JLabel meatsLabel;
    private javax.swing.JButton multiGrain;
    private javax.swing.JButton pepperJack;
    private javax.swing.JButton provolone;
    private javax.swing.JButton roastbeef;
    private javax.swing.JButton swiss;
    private javax.swing.JLabel toppingsMenuLabel;
    private javax.swing.JButton turkey;
    private javax.swing.JButton wheat;
    private javax.swing.JButton white;
    private javax.swing.JButton wholeGrain;
    // End of variables declaration//GEN-END:variables
}
